apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sql-generator
  template:
    metadata:
      labels:
        app: sql-generator
    spec:
      containers:
      - name: fastapi
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-secret
              key: groq_key
